"use client";

import { useState } from "react";
import type { Message, ResumeScore } from "@/lib/types";
import { parseBlock, parseAllBlocks } from "@/lib/protocolParser";
import { summarizeSession } from "@/lib/sessionLog";

interface ExportModalProps {
  currentResumeText: string | null;
  messages: Message[];
  resumeScore: ResumeScore | null;
  onClose: () => void;
}

// ── Extraction helpers ────────────────────────────────────────────────────────

interface StoryOutput {
  whyIB?: string;
  thread?: string;
  crystallizingMoment?: string;
}

interface NetworkingActions {
  actions: string[];
  template?: string;
}

function extractStory(messages: Message[]): StoryOutput | null {
  for (const m of [...messages].reverse()) {
    if (m.role !== "assistant") continue;
    const parsed = parseBlock<StoryOutput>(m.content, "story-output");
    if (parsed && (parsed.whyIB || parsed.thread)) return parsed;
  }
  return null;
}

function extractNetworkingActions(messages: Message[]): NetworkingActions | null {
  const allNetworking = messages.flatMap((m) => {
    if (m.role !== "assistant") return [];
    return parseAllBlocks<NetworkingActions>(m.content, "networking-actions");
  });
  if (!allNetworking.length) return null;
  // Merge all actions into one
  const merged: NetworkingActions = { actions: [] };
  for (const n of allNetworking) {
    merged.actions.push(...(n.actions ?? []));
    if (n.template) merged.template = n.template;
  }
  return merged.actions.length ? merged : null;
}

function formatStory(story: StoryOutput): string {
  const lines = [
    "WHY-IB STORY",
    "Generated by IB Resume Coach",
    "─".repeat(40),
    "",
  ];
  if (story.crystallizingMoment) {
    lines.push("CRYSTALLIZING MOMENT");
    lines.push(story.crystallizingMoment);
    lines.push("");
  }
  if (story.whyIB) {
    lines.push("WHY IB");
    lines.push(story.whyIB);
    lines.push("");
  }
  if (story.thread) {
    lines.push("YOUR THREAD");
    lines.push(story.thread);
    lines.push("");
  }
  return lines.join("\n");
}

function formatNetworking(n: NetworkingActions): string {
  const lines = [
    "NETWORKING ACTION LIST",
    "Generated by IB Resume Coach",
    "─".repeat(40),
    "",
    "ACTIONS",
    ...n.actions.map((a, i) => `${i + 1}. ${a}`),
  ];
  if (n.template) {
    lines.push("");
    lines.push("EMAIL TEMPLATE");
    lines.push(n.template);
  }
  return lines.join("\n");
}

function formatSessionJson(
  messages: Message[],
  resumeScore: ResumeScore | null,
  currentResumeText: string | null
): string {
  const summary = summarizeSession();
  return JSON.stringify(
    {
      exportedAt: new Date().toISOString(),
      summary,
      resumeScore,
      currentResumeText,
      messages: messages.filter((m) => m.content !== "__resume_uploaded__"),
    },
    null,
    2
  );
}

// ── Download helper ───────────────────────────────────────────────────────────

function downloadText(filename: string, text: string) {
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

// ── Component ─────────────────────────────────────────────────────────────────

type ToastState = { text: string; ok: boolean } | null;

export default function ExportModal({
  currentResumeText,
  messages,
  resumeScore,
  onClose,
}: ExportModalProps) {
  const [toast, setToast] = useState<ToastState>(null);

  const story = extractStory(messages);
  const networking = extractNetworkingActions(messages);

  function showToast(text: string, ok = true) {
    setToast({ text, ok });
    setTimeout(() => setToast(null), 2500);
  }

  const items = [
    {
      label: "Resume (.txt)",
      desc: "Your edited resume with all applied improvements",
      note: null as string | null,
      available: !!currentResumeText,
      unavailableReason: "Upload a resume first",
      onClick: () => {
        downloadText("resume-edited.txt", currentResumeText!);
        showToast("Resume downloaded");
      },
      icon: (
        <path
          strokeLinecap="round" strokeLinejoin="round"
          d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
        />
      ),
    },
    {
      label: "Why-IB Story (.txt)",
      desc: story
        ? "Your narrative — ready to use as cover letter foundation"
        : "Develop your story with the coach first",
      note: story ? null : 'Use the \u201cDevelop Story\u201d button in the sidebar',
      available: !!story,
      unavailableReason: null,
      onClick: () => {
        downloadText("why-ib-story.txt", formatStory(story!));
        showToast("Story downloaded");
      },
      icon: (
        <path
          strokeLinecap="round" strokeLinejoin="round"
          d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"
        />
      ),
    },
    {
      label: "Networking Actions (.txt)",
      desc: networking
        ? `${networking.actions.length} concrete action${networking.actions.length !== 1 ? "s" : ""} + email template`
        : "Ask for a concrete networking plan first",
      note: networking ? null : 'Use the \u201cNetworking Plan\u201d button in the sidebar',
      available: !!networking,
      unavailableReason: null,
      onClick: () => {
        downloadText("networking-action-list.txt", formatNetworking(networking!));
        showToast("Networking plan downloaded");
      },
      icon: (
        <path
          strokeLinecap="round" strokeLinejoin="round"
          d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z"
        />
      ),
    },
    {
      label: "Full Session (.json)",
      desc: "All messages, score, resume, and event summary",
      note: null,
      available: messages.length > 0,
      unavailableReason: "Start a session first",
      onClick: () => {
        downloadText(
          "ib-coach-session.json",
          formatSessionJson(messages, resumeScore, currentResumeText)
        );
        showToast("Session exported");
      },
      icon: (
        <path
          strokeLinecap="round" strokeLinejoin="round"
          d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"
        />
      ),
    },
  ];

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm"
      onClick={onClose}
    >
      <div
        className="w-full max-w-md rounded-2xl border border-stone-800 bg-stone-950 p-6 shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="mb-5 flex items-center justify-between">
          <div>
            <h2 className="text-base font-semibold text-stone-100">Export Pack</h2>
            <p className="mt-0.5 text-xs text-stone-500">
              Download your session artifacts
            </p>
          </div>
          <button
            onClick={onClose}
            className="rounded-lg p-1.5 text-stone-500 hover:bg-stone-800 hover:text-stone-300 transition"
          >
            <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Items */}
        <div className="space-y-2">
          {items.map((item) => (
            <div
              key={item.label}
              className={`flex items-center justify-between gap-3 rounded-xl border px-4 py-3 transition ${
                item.available
                  ? "border-stone-800 hover:border-stone-700 hover:bg-stone-900/60"
                  : "border-stone-900 opacity-50"
              }`}
            >
              <div className="flex items-center gap-3 min-w-0">
                <svg
                  className="h-4 w-4 shrink-0 text-stone-400"
                  fill="none" viewBox="0 0 24 24"
                  stroke="currentColor" strokeWidth={1.5}
                >
                  {item.icon}
                </svg>
                <div className="min-w-0">
                  <p className="text-sm font-medium text-stone-200">{item.label}</p>
                  <p className="truncate text-xs text-stone-500">{item.desc}</p>
                </div>
              </div>
              {item.available ? (
                <button
                  onClick={item.onClick}
                  className="ml-2 shrink-0 rounded-lg bg-amber-600 px-3 py-1.5 text-xs font-medium text-white transition hover:bg-amber-500"
                >
                  Download
                </button>
              ) : (
                <span className="ml-2 shrink-0 rounded-lg bg-stone-800 px-3 py-1.5 text-xs text-stone-600">
                  Not ready
                </span>
              )}
            </div>
          ))}
        </div>

        {/* Toast */}
        {toast && (
          <div
            className={`mt-4 rounded-lg px-4 py-2.5 text-center text-sm font-medium transition ${
              toast.ok
                ? "bg-emerald-900/40 text-emerald-400"
                : "bg-red-900/40 text-red-400"
            }`}
          >
            {toast.text}
          </div>
        )}

        <p className="mt-4 text-center text-xs text-stone-700">
          Nothing is sent to any server. All exports are local.
        </p>
      </div>
    </div>
  );
}
